### ISSUE TITLE
Find PE command not working 

### ISSUE THREAD

**Issue by zerodark** [pidydx/SMRT#1]
trying "Find PE" command it will give following error 

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "SMRT in /home/user1/.config/sublime-text-3/Installed Packages/SMRT.sublime-package", line 424, in run
TypeError: object of type 'NoneType' has no len()

**Comment by pidydx** [comment]
I just pushed a fix for this, but it only really stops it from throwing the exception.  It appears the problem is that you have no data highlighted when running FindPE related commands.  Find PE, Brute XOR Find PE, and PE Scanner require a selection of Hex format data.
